public class MacroDAO {

    @auraenabled
    public Long deskMacroId;
    @auraenabled
    public String name;
    @auraenabled
    public String description;
    @auraenabled
    public String sfMacroId;
    @auraenabled
    public Integer totalDeskMacros;
    @auraenabled
    public Integer startPosition;
    @auraenabled
    public Integer endPosition;
 	@auraenabled   
    public List<MacroActionDAO> actions;
   

}