public class UserDAO {
    @auraenabled
    public String name;
    @auraenabled
    public String firstName;
    @auraenabled
    public String lastName;
    @auraenabled
    public String deskUserId;
    @auraenabled
    public String sfUserId;
    @auraenabled
    public Boolean inSalesforce;
    @auraenabled
    public Boolean inDesk;
    @auraenabled
    public Boolean isManual;
    @auraenabled
    public String email;
    @auraenabled
    public String sfUsername;
    @auraenabled
    public String sfProfileId;
    @auraenabled
    public String sfProfileName;
    @auraenabled
    public Boolean isActive;
    @auraenabled
    public String errorStatusCode;
	@auraenabled
    public String errorMessage;
    @auraenabled
    public String errorField;
    @auraenabled
    public String emailErrorStatusCode;
	@auraenabled
    public String emailErrorMessage;
    @auraenabled
    public Boolean selected;
}